In [1]:
#python script dalam model.py
#package = kumpulan modul
#NumPy.org

In [ ]:
import pkg.mod1
from pkg.mod1 import foo

In [7]:
#!conda install numpy
#!conda list numpy
#!conda --version
#!conda list
#!pip install numpy

In [1]:
!conda list numpy

# packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
numpy                     1.18.5           py38h6530119_0  
numpy-base                1.18.5           py38hc3f5095_0  
numpydoc                  1.1.0                      py_0  


In [4]:
!conda --version

conda 4.8.3


In [8]:
import numpy as np

In [10]:
np.__version__

'1.18.5'

In [11]:
#Numpy, Pandas, Scipy, matplotlib, scikit-learn

In [ ]:
## Array
#Y for code
#m for markdown

##Array

In [37]:
arrl = np.array([[1, 2,3],[4,5,6],[7,8,9],[10,11,12]]) #dtype='str' ubah ke string
print(arrl)
#bentuk matriks

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [23]:
print(arrl[1])
print(arrl[-1])

[4 5 6]
[10 11 12]


In [24]:
list1 = [[1, 2,3],[4,5,6],[7,8,9],[10,11,12]]
print(list1)
#bentuk baris

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]


In [34]:
list1[0][0], list1[1][0], list1[2][0], list1[3][0]

(1, 4, 7, 10)

In [31]:
print(arrl[0,0])
print(arrl[0])
print(arrl[:,0]) #column
print(arrl[:,1])

1
[1 2 3]
[ 1  4  7 10]
[ 2  5  8 11]


In [38]:
arrl.dtype, type(arrl)

(dtype('int32'), numpy.ndarray)

In [41]:
arr2=np.array([[0.1,.2],[0.3,.4]])
print(arr2)
print(arr2.dtype)

[[0.1 0.2]
 [0.3 0.4]]
float64


In [46]:
arr3 = np.array([
    [
        [1,2,3],
        [11,22,33]
    ],
    [
        [4,5,6],
        [44,55,66]
    ]    
])
print(arr3)


[[[ 1  2  3]
  [11 22 33]]

 [[ 4  5  6]
  [44 55 66]]]


In [48]:
# shape of array
print('shape of arrl:', arrl.shape)
print('shape of arr2:', arr2.shape)
print('shape of arr3:', arr3.shape)
print('dimension of arr1:', arrl.ndim)
print('dimension of arr2:', arr2.ndim)
print('dimension of arr3:', arr3.ndim)



shape of arrl: (4, 3)
shape of arr2: (2, 2)
shape of arr3: (2, 2, 3)
dimension of arr1: 2
dimension of arr2: 2
dimension of arr3: 3


In [49]:
np.array([[1,2,3],[1,2]])


array([list([1, 2, 3]), list([1, 2])], dtype=object)

In [56]:
arr_zeros_1 = np.zeros(10)
arr_zeros_2 = np.zeros((10,5))
arr_zeros_3 = np.zeros([5,10,10])

print(arr_zeros_1, arr_zeros_1.shape)
print('--')
print(arr_zeros_2, arr_zeros_2.shape)
print('--')
print(arr_zeros_3, arr_zeros_3.shape)
print('--')

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] (10,)
--
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] (10, 5)
--
[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 

In [57]:
arr_ones_1 = np.ones(10)
arr_ones_2 = np.ones((10,5))
arr_ones_3 = np.ones([5,10,10])

print(arr_ones_1, arr_ones_1.shape)
print('--')
print(arr_ones_2, arr_ones_2.shape)
print('--')
print(arr_ones_3, arr_ones_3.shape)
print('--')

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] (10,)
--
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] (10, 5)
--
[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 

In [62]:
arr_empty = np.empty((7,2))
print(arr_empty)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [66]:
print(np.arange(0,20))
print(np.arange(0,20,5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  5 10 15]


In [69]:
arr_one=np.array([1,2,3,4,5])
arr_one

array([1, 2, 3, 4, 5])

In [71]:
np.append(arr_one,10) #nambah dimensi

array([ 1,  2,  3,  4,  5, 10])

In [80]:
np.append(arrl, [[13,14,15],[16,17,18]], axis=0)
#nambah baris, harus sama 3 isinya

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [81]:
np.append(arrl, [[13],[14],[15],[16]], axis=1)
#nambah kolom, harus sama 4 isinya

array([[ 1,  2,  3, 13],
       [ 4,  5,  6, 14],
       [ 7,  8,  9, 15],
       [10, 11, 12, 16]])

In [82]:
arr_ones_3.shape

(5, 10, 10)

In [88]:
np.append(arr_ones_3, np.zeros((1,10,10)), axis=0) #.shape

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]

In [90]:
arr_12 = np.arange(12)+1
print(arr_12)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [91]:
arrl

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [96]:
np.delete(arrl,0, axis=0) #axis = dimesi

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [97]:
arr_unsorted = np.array([4,1,5,2,8,12,77,13])
print(arr_unsorted)
np.sort(arr_unsorted)

[ 4  1  5  2  8 12 77 13]


array([ 1,  2,  4,  5,  8, 12, 13, 77])

In [101]:
arrl[0] = [7, 1, 11]
arrl

array([[ 7,  1, 11],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [102]:
np.sort(arrl)

array([[ 1,  7, 11],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [104]:
print(np.sort(arrl, axis=0))

[[ 4  1  6]
 [ 7  5  9]
 [ 7  8 11]
 [10 11 12]]


In [106]:
arr_one

array([1, 2, 3, 4, 5])

In [107]:
arr_one.shape, arrl.shape

((5,), (4, 3))

In [109]:
vector_col = np.array([[1],[2],[3],[4],[5]])
print(vector_col, vector_col.shape)

[[1]
 [2]
 [3]
 [4]
 [5]] (5, 1)


In [114]:
arrl

array([[ 7,  1, 11],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [113]:
print(np.reshape(arrl, (3,4)))
print('----')
print(np.reshape(arrl, (2,6)))
print('----')
print(np.reshape(arrl, (2,2,3)))
print('----')
print(np.reshape(arrl, (1,4,3)))
print('----')
print(np.reshape(arrl, (4,1,3)))

[[ 7  1 11  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
----
[[ 7  1 11  4  5  6]
 [ 7  8  9 10 11 12]]
----
[[[ 7  1 11]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
----
[[[ 7  1 11]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
----
[[[ 7  1 11]]

 [[ 4  5  6]]

 [[ 7  8  9]]

 [[10 11 12]]]


In [ ]:
#np.newaxis #nambah dimensi
#np.expand_dims 

In [118]:
print(arrl[:, np.newaxis].shape)
print(arrl[..., np.newaxis].shape)

(4, 1, 3)
(4, 3, 1)


In [121]:
arrl.flatten()

array([ 7,  1, 11,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [119]:
arrl[arrl>5]

array([ 7, 11,  6,  7,  8,  9, 10, 11, 12])

In [122]:
arrl[arrl%2==0]

array([ 4,  6,  8, 10, 12])

In [124]:
arrl[(arrl>5) & (arrl<17)] #and

array([ 7, 11,  6,  7,  8,  9, 10, 11, 12])

In [125]:
arrl[(arrl%2==0) | (arrl%3==0)] #or

array([ 4,  6,  8,  9, 10, 12])

In [127]:
np.transpose(arrl)

array([[ 7,  4,  7, 10],
       [ 1,  5,  8, 11],
       [11,  6,  9, 12]])

In [129]:
np.expand_dims(arrl, axis=1)

array([[[ 7,  1, 11]],

       [[ 4,  5,  6]],

       [[ 7,  8,  9]],

       [[10, 11, 12]]])

In [130]:
#np.vstack
#np.hstack

In [131]:
arrqq = arrl*10
print(arrl)
print(arrqq)

[[ 7  1 11]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 70  10 110]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


In [135]:
print(np.concatenate((arrl,arrqq))) #digabung
print(np.concatenate((arrl,arrqq), axis=1))

[[  7   1  11]
 [  4   5   6]
 [  7   8   9]
 [ 10  11  12]
 [ 70  10 110]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
[[  7   1  11  70  10 110]
 [  4   5   6  40  50  60]
 [  7   8   9  70  80  90]
 [ 10  11  12 100 110 120]]


In [ ]:
#np.hsplit

In [136]:
arrl.sum(), np.sum(arrl), sum(arrl)

(91, 91, array([28, 25, 38]))

In [139]:
print(arrl)
print(arrl.sum(axis=0))
print(arrl.sum(axis=1))

[[ 7  1 11]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[28 25 38]
[19 15 24 33]


In [142]:
print(arrl.std(), arrl.mean(), arrl.max(), arrl.min())

3.121386800054674 7.583333333333333 12 1


In [143]:
arrl.shape, arrl.shape

((4, 3), (4, 3))

In [150]:
print(arrl+arrl) #penjumlahan
print(arrl.dot(arrqq.T)) #perkalian matrix
print(np.multiply(arrl,arrqq))
arrl*arrqq

[[14  2 22]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]
[[1710  990 1560 2130]
 [ 990  770 1220 1670]
 [1560 1220 1940 2660]
 [2130 1670 2660 3650]]
[[ 490   10 1210]
 [ 160  250  360]
 [ 490  640  810]
 [1000 1210 1440]]


array([[ 490,   10, 1210],
       [ 160,  250,  360],
       [ 490,  640,  810],
       [1000, 1210, 1440]])

In [151]:
arrl.dot(np.array([3,3,3]))

array([57, 45, 72, 99])

In [156]:
np.matmul(arrl,np.array([3,3,3]))

array([57, 45, 72, 99])

In [171]:
a = np.ones([5,1])
c = np.ones([1])
print(a)
print(c)
np.dot(a,c)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[1.]


array([1., 1., 1., 1., 1.])